/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SudokuGUI.java
 *
 * Created on 23/05/2011, 15:12:03
 */

package frames;

/**
 *
 * @author daniel
 */
public class SudokuGUI extends javax.swing.JFrame {

    /** Creates new form SudokuGUI */
    public SudokuGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jSudokuGrid = new javax.swing.JTable();
        jSudokuMenuBar = new javax.swing.JMenuBar();
        SudokuMenu = new javax.swing.JMenu();
        Limpar = new javax.swing.JMenuItem();
        Resolver = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSudokuGrid.setAutoCreateRowSorter(true);
        jSudokuGrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jSudokuGrid.setFont(new java.awt.Font("Liberation Serif", 1, 36)); // NOI18N
        jSudokuGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jSudokuGrid.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jSudokuGrid.setColumnSelectionAllowed(true);
        jSudokuGrid.setDropMode(javax.swing.DropMode.ON_OR_INSERT_ROWS);
        jSudokuGrid.setFillsViewportHeight(true);
        jSudokuGrid.setFocusTraversalPolicyProvider(true);
        jSudokuGrid.setGridColor(java.awt.Color.darkGray);
        jSudokuGrid.setMinimumSize(new java.awt.Dimension(135, 300));
        jSudokuGrid.setRowHeight(36);
        jSudokuGrid.setSurrendersFocusOnKeystroke(true);
        jSudokuGrid.setUpdateSelectionOnSort(false);
        jSudokuGrid.setVerifyInputWhenFocusTarget(false);
        jSudokuGrid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSudokuGridKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jSudokuGrid);
        jSudokuGrid.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        SudokuMenu.setText("Sudoku");

        Limpar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        SudokuMenu.add(Limpar);

        Resolver.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        Resolver.setText("Resolver");
        Resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResolverActionPerformed(evt);
            }
        });
        SudokuMenu.add(Resolver);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Resolver mostrando passos");
        SudokuMenu.add(jMenuItem3);

        jSudokuMenuBar.add(SudokuMenu);

        Help.setText("Help");

        jMenuItem4.setText("Sobre");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Help.add(jMenuItem4);

        jSudokuMenuBar.add(Help);

        setJMenuBar(jSudokuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jSudokuGridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSudokuGridKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jSudokuGridKeyPressed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here:
        for(int i=0; i< 9 ; i++){
            for(int j = 0; j< 9; j++){
                jSudokuGrid.setValueAt(null, i, j);
            }
        }
    }//GEN-LAST:event_LimparActionPerformed

    private void ResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResolverActionPerformed
        // TODO add your handling code here:

        // Exemplo de como chamar o metodo Resolver
        // nesse caso ao clicar em resolver o grid sera pintado de azul
        // e as celulas sao preenchidas com um exemplo
        

        jSudokuGrid.setGridColor(java.awt.Color.BLUE);
        /*sudokusolver*/
        for (int i = 0; i < 9 ; i++){
            for (int j=0 ; j< 9; j++){
                if (jSudokuGrid.getValueAt(i, j) == null )
                    jSudokuGrid.setValueAt(i + 1, i, j);
            }
        }
        

    }//GEN-LAST:event_ResolverActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem Limpar;
    private javax.swing.JMenuItem Resolver;
    private javax.swing.JMenu SudokuMenu;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jSudokuGrid;
    private javax.swing.JMenuBar jSudokuMenuBar;
    // End of variables declaration//GEN-END:variables

}
